#!/bin/bash
#steven guo
#this program sorts and filters the people in donors file. it changes the last name savage to savauge, put list of donor with area code 916 to specialAreaCode
#put first name starting with c or e into CEnames
#put people who donated over 500 into file over500

#file names
FILE="donors"
SPL="specialAreaCode"
NAMES="CEnames"
OVER="over500"

#writing headres into files
printf '%-15s %-14s %-7s %-7s %s\n' "NAME" "PHONE" "JAN" "FEB" "MAR" > $SPL
printf '%-15s %-14s %-7s %-7s %s\n' "NAME" "PHONE" "JAN" "FEB" "MAR" > $NAMES
printf '%-15s %-13s\n' "NAME" "PHONE" > $OVER

#this reads input from the donors file
while read var
do
   name=$(echo $var | awk  '{print $1}')
   ph=$(echo $var | awk -F ":" '{print $2}')
   jd=$(echo $var | awk -F ":" '{print $3}')
   fd=$(echo $var | awk -F ":" '{print $4}')
   md=$(echo $var | awk -F ":" '{print $5}')


#this gets the area code from phone number
   code=$(echo $ph | cut -d "(" -f2 | cut -d ")" -f1)

  if [ "$code" == "916" ]; then

       printf '%-15s %-14s %-7s %-7s %-7s\n' "$name" "$ph" "$""$jd" "$""$fd" "$""$md" >> $SPL
  fi 

#if first  name starts with C or E, then writing the contents into file
   if [[ "${name:0:1}" == 'E' || "${name:0:1}" == 'C' ]]; then

       printf '%-15s %-14s %-7s %-7s %-7s\n' "$name" "$ph" "$""$jd" "$""$fd" "$""$md" >> $NAMES
   fi
#this sums up the total donated and ov sets the conditional statement for donation over 500
sum=$(($jd + $fd + $md))
ov=500
if (($sum > $ov)); then
   printf '%-15s %-8s\n' "$name" "$ph" >> $OVER 
fi
done < $FILE

