quadreq:QEmake.c prno.o prone.o prtwo.o radicand.o
	gcc -o quadreq QEmake.c prno.o prone.o prtwo.o radicand.o -lm
prno.o:prno.c QE.h
	gcc -c prno.c
prone.o:prone.c QE.h
	gcc -c prone.c
prtwo.o:prtwo.c QE.h
	gcc -c prtwo.c
radicand.o:radicand.c QE.h
	gcc -c radicand.c
